version: '3'

services:
  base: &base
    container_name: cw_base
    # image: chatwoot/chatwoot:latest-ce
    image: chatwoot/chatwoot:latest
    env_file: .env ## Change this file for customized env variables
    volumes:
      - ./data/storage:/app/storage

  rails:
    <<: *base
    container_name: cw_rails
    restart: always
    depends_on:
      - postgres
      - redis
    ports:
      - '127.0.0.1:3000:3000'
    environment:
      - NODE_ENV=${RAILS_ENV}
      - RAILS_ENV=${RAILS_ENV}
      - INSTALLATION_ENV=docker
      - FRONTEND_URL=http://0.0.0.0:3000
    entrypoint: docker/entrypoints/rails.sh
    command: ['bundle', 'exec', 'rails', 's', '-p', '3000', '-b', '0.0.0.0']

  sidekiq:
    <<: *base
    container_name: cw_sidekiq
    restart: always
    depends_on:
      - postgres
      - redis
    environment:
      - NODE_ENV=${RAILS_ENV}
      - RAILS_ENV=${RAILS_ENV}
      - INSTALLATION_ENV=docker
    command: ['bundle', 'exec', 'sidekiq', '-C', 'config/sidekiq.yml']

  postgres:
    container_name: cw_postgres
    image: postgres:12
    restart: always
    ports:
      - '127.0.0.1:5432:5432'
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DATABASE}
      - POSTGRES_USER=${POSTGRES_USERNAME}
      # Please provide your own password.
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

  redis:
    container_name: cw_redis
    image: redis:alpine
    restart: always
    command: ["sh", "-c", "redis-server --requirepass \"$REDIS_PASSWORD\""]
    env_file: .env
    volumes:
      - ./data/redis:/data
    ports:
      - '127.0.0.1:6379:6379'
